    - name: Ensure Timezone set to GMT
      copy: content="Etc/GMT\n" dest=/etc/timezone owner=root group=root mode=0644
      register: timezone

    - name: Reconfigure Timezone Data
      shell: dpkg-reconfigure -f noninteractive tzdata
      when: timezone.changed
